apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-{{ .Values.deploymentType }}
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
  namespace: "argocd"
spec:
  destination:
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "charts/bootloader"
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: "HEAD"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        - /releases/global/app-of-apps-{{ .Values.deploymentType }}.yaml
        - /releases/{{ .Values.environment }}/app-of-apps-{{ .Values.deploymentType }}.generated.yaml
        - /releases/{{ .Values.environment }}/app-of-apps-{{ .Values.deploymentType }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
