grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
  ingress:
    enabled: true
    ingressClassName: nginx # This is the default ingress class name
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    path: /
  persistence:
    enabled: true
  serviceAccount:
    name: grafana-sa
  serviceMonitor:
    enabled: true
