apps:
  - name: cert-manager
  - name: external-secrets
  - name: tracee
  - name: trivy-operator
    namespace: trivy-system
  - ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        jqPathExpressions:
          - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
    name: istio-base
    namespace: istio-system
  - ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istio-validator-istio-system
        jqPathExpressions:
          - .webhooks[] | select(.name == "rev.validation.istio.io") | .failurePolicy
    name: istiod
    namespace: istio-system
deploymentType: security
repoURL: "git@github.com:number3ai/caprica.git"
