karpenter:
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  # Karpenter node template settings
  defaultProvisioner:
    limits:
      cpu: 1000
      memory: 4000Gi
    requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: "In"
        values: ["t3.medium", "t3.large"]
  logging:
    level: info
    format: json
  nodeTerminationHandler:
    enable: true
    queueName: "karpenter-queue"
  rbac:
    create: true
  serviceAccount:
    name: karpenter-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<karpenter-irsa-role>
