apiVersion: v2
name: prom-crds
description: A Helm chart for prometheus crds

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "v0.76.0"

dependencies:
  - name: prometheus-operator-crds
    version: 14.0.0
    repository: https://prometheus-community.github.io/helm-charts
