apiVersion: v2
type: application
name: istiod
description: A Helm chart for istiod
version: 1.0.0
appVersion: 1.23.1
maintainers:
  - name: Brandon Helms
    email: bhelms85@gmail.com
keywords:
  - security
  - istio
dependencies:
  - name: istiod
    version: 1.23.1
    repository: https://istio-release.storage.googleapis.com/charts
