prometheus:
  server:
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    persistentVolume:
      enabled: true
      size: 8Gi
      
